version: '3.1'
services:
  postgres-go-rest:
    container_name: postgres-go-web
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_rest
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
#version: '3'
#services:
#  postgres:
#    image: "postgres"
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: root
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql

#  pgadmin-compose:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "osvald.soza@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "osf77"
#    ports:
#      - "54321:80"
#    depends_on:
#      - postgres